name: Build

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Setup Cachix
        uses: cachix/cachix-action@v13
        with:
          name: devenv
      - name: Install devenv
        run: nix-env -if https://install.devenv.sh/latest
      - name: Run tests
        run: devenv shell -- tests

  templates:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        template:
          - name: default
            test: nix develop --accept-flake-config -c python --version
          - name: devenv
            test: nix develop --accept-flake-config --impure -c python --version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Replace inputs on templates
        run: sed -i 's/github:sestrella\/asdf2nix/github:sestrella\/asdf2nix\/${{ github.sha }}/g' templates/*/flake.nix
      - name: Create a temporary directory
        run: echo "tmpdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"
        id: mktemp
      - name: Scaffold a new project
        run: nix flake init -t ${{ github.workspace }}#${{ matrix.template.name }}
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - name: Run smoke test
        run: ${{ matrix.template.test }}
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}

