name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix eval --impure .#tests
        working-directory: tests

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: echo "tmpdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"
        id: mktemp
      - run: nix flake init -t "${{ github.workspace }}#default"
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: nix develop -c python --version
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
