name: Publish

on: push

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v1.0.0
          - v1.1.0
          - v2.0.0
          - v2.1.0
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.version }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Publish flake
        uses: DeterminateSystems/flakehub-push@main
        with:
          tag: ${{ matrix.version }}
          visibility: listed
