name: Publish

on: push
  # push:
  #   tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: The existing tag to publish
  #       type: string
  #       required: true

concurrency:
  group: publish
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  # https://flakehub.com/new
  flakehub:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref_name }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8
      - name: Publish flake
        uses: DeterminateSystems/flakehub-push@v3
        with:
          tag: ${{ inputs.tag || github.ref_name }}

  # https://flakestry.dev/publish
  flakestry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v1.0.0
          - v1.1.0
          - v2.0.0
          - v2.1.0
      fail-fast: true
    steps:
      - name: Publish flake
        uses: flakestry/flakestry-publish@main
        with:
          version: ${{ matrix.version }}
