name: Publish

on: push

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v1.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Publish flake
        uses: DeterminateSystems/flakehub-push@main
        with:
          tag: v1.0.0
          visibility: unlisted
